### Create vehicle
POST {{host}}/v1/vehicles
Content-Type: application/json

{
  "vehicleName": "hyundai",
  "isActive": true
}

### Get vehicle by id
GET {{host}}/v1/vehicles/1

### Get available vehicles - vehicles that are either CREATED, RUNNING, PAUSED or STOPPED
GET {{host}}/v1/vehicles/available

### Get all vehicles
GET {{host}}/v1/vehicles

### Update vehicle name
POST http://localhost:1000/v1/vehicles/1/update
Content-Type: application/json

{
  "vehicleName": "hyundai",
  "isActive": true
}

### Delete vehicle
DELETE {{host}}/v1/vehicles/1

### Upload vehicle image
POST {{host}}/v1/vehicles/image/2/upload
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image"; filename="electric-vehicle-2.jpg"

< /Users/bogdanjovanovic/Pictures/auticparkic images/electric-vehicle-2.jpg
--boundary
Content-Disposition: form-data; name="image"

1
--boundary

### Create ride
POST {{host}}/v1/rides/create?vehicleId=1

### Start ride
POST {{host}}/v1/rides/1/start

### Pause ride
POST {{host}}/v1/rides/1/pause

### Stop ride
POST {{host}}/v1/rides/1/stop

### Finish ride
POST {{host}}/v1/rides/1/finish

### Restart ride
POST {{host}}/v1/rides/1/restart

### Get ride's elapsed time
GET {{host}}/v1/rides/1/elapsed-time

### Get unfinished rides
GET {{host}}/v1/rides/unfinished

### Update ride's elapsed time
POST {{host}}/v1/rides/2?elapsedTime=500
