services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpassword
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - 5432:5432
    networks:
      - auticparkicnetwork
    restart: unless-stopped
#  web:
#    image: bogdanjovanovic/auticparkic:latest
#    ports:
#      - 80:10000
#    networks:
#      - auticparkicnetwork
#    restart: always
#    environment:
#      - SPRING_PROFILES_ACTIVE=test
#    depends_on:
#      - db

networks:
  auticparkicnetwork:
    name: auticparkicnetwork
    driver: bridge

volumes:
  db:
