services:
  db:
    container_name: postgres
    image: postgres:15.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpassword
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - 5432:5432
    networks:
      - auticparkicnetwork
    restart: unless-stopped
#  auticparkic-api:
#    image: bogdanjovanovic/auticparkic-api:latest
#    container_name: auticparkic-api
#    ports:
#      - 10000:10000
#    environment:
#      - SPRING_PROFILES_ACTIVE=test
#    restart: unless-stopped
#    networks:
#      - auticparkicnetwork
#    depends_on:
#      - db
#  auticparkic-frontend:
#    image: bogdanjovanovic/auticparkic-frontend:latest
#    container_name: auticparkic-react
#    build:
#      context: frontend/
#      args:
#        API_BASE_URL: http://localhost:10000/api
#    ports:
#      - 80:3000
#    restart: unless-stopped
#    networks:
#      - auticparkicnetwork
#    depends_on:
#      - auticparkic-api

networks:
  auticparkicnetwork:
    name: auticparkicnetwork
    driver: bridge

volumes:
  db:
