# set SPRING_PROFILES_ACTIVE=test as active profile
# and override the values from application.yml

spring:
  datasource:
    jdbc-url: "jdbc:postgresql://postgres:5432/autic_parkic" # postgres is the name of the container
