# set SPRING_PROFILES_ACTIVE=test as active profile
# and override the values from application.yml

#app:
#  datasource:
#    main:
#      jdbc-url: "jdbc:postgresql://postgres:5432/autic_parkic"
#      username: "postgres"
#      password: "rootpassword"
#      pool-size: 30

logging:
  level:
    org:
      springframework:
        jdbc: "DEBUG"

aws:
  region: "eu-central-1"
  s3:
    mock: false
    buckets:
      vehicles: "auticparkic-vehicles-test"
