server:
  port: 10000

spring:
  datasource:
    jdbc-url: "jdbc:postgresql://localhost:5432/autic_parkic"
    username: "postgres"
    password: "rootpassword"
    pool-size: 30
    driver-class-name: org.postgresql.Driver
  profiles:
    active: "dev" # can be overridden through env variable: SPRING_PROFILES_ACTIVE=dev
  servlet:
    multipart:
      max-file-size: "10MB"
      max-request-size: "10MB"
  codec:
    max-in-memory-size: "10MB"

logging:
  level:
    com:
      jovanovicbogdan:
        auticparkic: "DEBUG"
    org:
      springframework:
        jdbc: "DEBUG"

# spring boot actuator
#management:
  #  server:
  #    port: 10000
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#        exclude: "env,beans"

springdoc:
  swagger-ui:
    path: "/swagger"
  show-actuator: true

aws:
  region: "eu-central-1"
  s3:
    mock: true
    buckets:
      vehicles: "auticparkic-vehicles-test"
